# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Archive-Tar
version:      1.08
version_from: lib/Archive/Tar.pm
installdirs:  site
requires:
    File::Spec:                    0.82
    Test::Harness:                 2.26
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
